name: my firest workflow
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # lancement manuel
jobs:
  build:
    runs-on: ubunto-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      
    - run: npm install
    - run: gulp build
    - uses: actions/upload-artifact@v1
      with:
        name: MyPackage
        path: dest
